const productActionType = {
  GET_IMAGE_REQUEST: "GET_IMAGE_REQUEST",
  GET_IMAGE_SUCCESS: "GET_IMAGE_SUCCESS",
  GET_IMAGE_FAILURE: "GET_IMAGE_FAILURE",

  // Productlist
  GET_PRODUCT_LIST_REQUEST: "GET_PRODUCT_LIST_REQUEST",
  GET_PRODUCT_LIST_SUCCESS: "GET_PRODUCT_LIST_SUCCESS",
  GET_PRODUCT_LIST_FAILURE: "GET_PRODUCT_LIST_FAILURE",
};


export default productActionType